import React,{useEffect,useMemo,useState} from "react";
import {createClient} from "@supabase/supabase-js";
import {ArrowRight,Bike,Box,Check,CheckCircle2,Clock3,LocateFixed,LogIn,LogOut,MapPin,Menu,MessageCircle,Navigation,Package,Phone,RefreshCw,Send,ShieldCheck,Truck,UserPlus,X,WalletCards,LockKeyhole,AlertTriangle,Radio} from "lucide-react";

const url=import.meta.env.VITE_SUPABASE_URL, key=import.meta.env.VITE_SUPABASE_ANON_KEY;
const supabase=url&&key?createClient(url,key):null;
const API_BASE=(import.meta.env.VITE_API_BASE_URL||"https://femmadexdrive.onrender.com/api").replace(/\/+$/,"");
const ADMIN_HOST=import.meta.env.VITE_ADMIN_HOST||"femmadexdive.netlify.app";

const api=(path,body={},token)=>fetch(`${API_BASE}/${path}`,{method:"POST",headers:{"Content-Type":"application/json",...(token?{Authorization:`Bearer ${token}`}:{})},body:JSON.stringify(body)}).then(async r=>{const d=await r.json().catch(()=>({}));if(!r.ok)throw new Error(d.error||"Request failed");return d});
const money=n=>`₦${Number(n||0).toLocaleString()}`;
const clean=s=>String(s||"").replace(/[<>]/g,"").trim();
const fmt=d=>d?new Date(d).toLocaleString([],{dateStyle:"medium",timeStyle:"short"}):"—";
const statusLabels={searching:"Finding your rider",price_review:"Preparing your price",awaiting_payment:"Ready for secure payment",paid:"Payment confirmed",accepted:"Rider assigned",picked_up:"Package picked up",on_the_way:"On the way",at_door:"Arrived at destination",delivered:"Please confirm delivery",completed:"Delivered",cancelled:"Cancelled"};

function path(){let p=location.pathname.replace(/\/+$/,"")||"/"; if(p==="/rider")return"rider";if(p==="/track")return"track";if(p==="/admin")return"admin";if(p==="/payment-result")return"payment-result";return"customer"}
function go(p){history.pushState({}, "", p);dispatchEvent(new PopStateEvent("popstate"));scrollTo({top:0,behavior:"smooth"})}

function useSession(){
 const [session,setSession]=useState(null),[profile,setProfile]=useState(null),[loading,setLoading]=useState(!!supabase);
 useEffect(()=>{if(!supabase){setLoading(false);return}let mounted=true,authEventReceived=false;const {data}=supabase.auth.onAuthStateChange((_,nextSession)=>{authEventReceived=true;if(!mounted)return;setSession(nextSession);setLoading(false)});const timeout=setTimeout(()=>{if(mounted&&!authEventReceived)setLoading(false)},10000);supabase.auth.getSession().then(({data:result,error})=>{if(!mounted||authEventReceived)return;if(error)console.error("Could not restore Supabase session",error.message);setSession(result?.session||null);setLoading(false)}).catch(error=>{if(!mounted||authEventReceived)return;console.error("Could not restore Supabase session",error);setSession(null);setLoading(false)});return()=>{mounted=false;clearTimeout(timeout);data.subscription.unsubscribe()}},[]);
 useEffect(()=>{if(!supabase||!session){setProfile(null);return}let mounted=true;setProfile(null);(async()=>{const {data,error}=await supabase.from("profiles").select("*").eq("id",session.user.id).maybeSingle();if(error){console.error("Could not load user profile",error.message);return}if(!data||!mounted)return;if(data.role==="rider"){const {data:r,error:riderError}=await supabase.from("riders").select("*").eq("id",session.user.id).maybeSingle();if(riderError)console.error("Could not load rider profile",riderError.message);if(mounted)setProfile({...data,rider:r||null})}else if(mounted)setProfile(data)})();return()=>{mounted=false}},[session?.user?.id]);
 return {session,profile,loading}
}

export default function App(){
 const [page,setPage]=useState(path()),[modal,setModal]=useState(null),[toast,setToast]=useState(""),[menu,setMenu]=useState(false);
 const {session,profile,loading}=useSession();
 useEffect(()=>{const f=()=>setPage(path());addEventListener("popstate",f);return()=>removeEventListener("popstate",f)},[]);
 useEffect(()=>{if(toast){const t=setTimeout(()=>setToast(""),3500);return()=>clearTimeout(t)}},[toast]);
 const logout=async()=>{await supabase?.auth.signOut();go("/")};
 if(loading)return <Loading/>;
 if(!supabase)return <Setup/>;
 const adminHostOk=location.hostname===ADMIN_HOST||location.hostname==="localhost"||location.hostname==="127.0.0.1";
 return <><Header page={page} session={session} profile={profile} menu={menu} setMenu={setMenu} logout={logout} open={(role,mode)=>setModal({role,mode})}/>
 {page==="customer"&&<Customer session={session} profile={profile} open={(r,m)=>setModal({role:r,mode:m})} toast={setToast}/>}
 {page==="rider"&&<Rider session={session} profile={profile} open={(r,m)=>setModal({role:r,mode:m})} toast={setToast}/>}
 {page==="track"&&<Tracker/>}{page==="payment-result"&&<PaymentResult/>}
 {page==="admin"&&(!adminHostOk?<Blocked title="Private admin host required"/>:<Admin session={session} profile={profile} open={(r,m)=>setModal({role:r,mode:m})} toast={setToast}/>)}
 <Footer/>{modal&&<Auth role={modal.role} mode={modal.mode} close={()=>setModal(null)} toast={setToast}/>}
 {toast&&<div className="toast">{toast}</div>}</>
}

function Setup(){return <main className="center"><div className="setup"><b className="logo">FD</b><h1>Connect Supabase</h1><p>Add your Supabase URL and anon key to Netlify. This build contains no fake accounts or sample delivery records.</p><pre>VITE_SUPABASE_URL=...{"\n"}VITE_SUPABASE_ANON_KEY=...</pre></div></main>}
function Loading(){return <main className="center"><div className="spinner"/><p>Loading FemmaDexDrive…</p></main>}
function Blocked({title}){return <main className="center"><LockKeyhole size={42}/><h1>{title}</h1><p>The operations dashboard is available only on the configured admin hostname.</p></main>}

function Header({page,session,profile,menu,setMenu,logout,open}){
 return <header><button className="brand" onClick={()=>go("/")}><b className="logo">FD</b><span><strong>FemmaDexDrive</strong><small>Dispatch that gets there.</small></span></button><button className="hamb" onClick={()=>setMenu(!menu)}>{menu?<X/>:<Menu/>}</button><nav className={menu?"open":""}><button className={page==="customer"?"active":""} onClick={()=>go("/")}>Delivery</button><button className={page==="rider"?"active":""} onClick={()=>go("/rider")}>Riders</button><button onClick={()=>go("/track")}>Track</button>{session?<button onClick={logout}><LogOut size={15}/> Sign out</button>:<button className="primary" onClick={()=>open("customer","login")}><LogIn size={15}/> Sign in</button>}</nav></header>
}

function Customer({session,profile,open,toast}){
 const [orders,setOrders]=useState([]),[selected,setSelected]=useState(null),[busy,setBusy]=useState(false),[form,setForm]=useState({pickup:"",dropoff:"",description:"",weight:"",length:"",width:"",height:"",size:"medium"}),[quote,setQuote]=useState(null),[loc,setLoc]=useState(""),[message,setMessage]=useState(""),[chat,setChat]=useState([]),[contact,setContact]=useState(null);
 const token=useMemo(()=>session?.access_token,[session?.access_token]);
 const load=async()=>{if(!session)return;const {data}=await supabase.from("orders").select("*").eq("customer_id",session.user.id).order("created_at",{ascending:false});const rows=data||[];setOrders(rows);setSelected(current=>rows.find(o=>o.id===current?.id)||rows[0]||null)};
 useEffect(()=>{if(!session){setOrders([]);setSelected(null);return}load();const c=supabase.channel(`customer-orders-${session.user.id}`).on("postgres_changes",{event:"*",schema:"public",table:"orders",filter:`customer_id=eq.${session.user.id}`},load).subscribe();return()=>supabase.removeChannel(c)},[session?.user?.id]);
 useEffect(()=>{if(!selected||!session){setChat([]);setContact(null);return}let active=true;setChat([]);setContact(null);const c=supabase.channel(`chat-${selected.id}`).on("postgres_changes",{event:"INSERT",schema:"public",table:"chat_messages",filter:`order_id=eq.${selected.id}`},e=>setChat(x=>x.some(m=>m.id===e.new.id)?x:[...x,e.new])).subscribe();Promise.all([supabase.rpc("get_delivery_contacts",{p_order_id:selected.id}),supabase.from("chat_messages").select("*").eq("order_id",selected.id).order("created_at")]).then(([contacts,messages])=>{if(!active)return;if(contacts.error)toast(contacts.error.message);setContact(contacts.data?.[0]||null);if(messages.error){toast(messages.error.message);return}setChat(current=>{const byId=new Map(current.map(m=>[m.id,m]));for(const m of messages.data||[])byId.set(m.id,m);return [...byId.values()].sort((a,b)=>new Date(a.created_at)-new Date(b.created_at))})});return()=>{active=false;supabase.removeChannel(c)}},[selected?.id,session?.user?.id]);
 const locate=field=>{if(!navigator.geolocation)return toast("Location is not available.");setLoc(field);navigator.geolocation.getCurrentPosition(async p=>{try{const d=await fetch(`${API_BASE}/reverse-geocode?lat=${p.coords.latitude}&lng=${p.coords.longitude}`).then(r=>r.json());setForm(f=>({...f,[field]:d.address||`${p.coords.latitude},${p.coords.longitude}`}));toast("Location added.");}catch{toast("Could not resolve location.")}finally{setLoc("")}},()=>{setLoc("");toast("Location permission was not granted.")},{enableHighAccuracy:true,timeout:12000})};
 const getQuote=async e=>{e.preventDefault();if(!form.pickup||!form.dropoff||!form.description)return toast("Enter both addresses and package details.");setBusy(true);try{const d=await api("quote",{pickupAddress:clean(form.pickup),dropoffAddress:clean(form.dropoff),description:clean(form.description),weightKg:Number(form.weight)||0,lengthCm:Number(form.length)||0,widthCm:Number(form.width)||0,heightCm:Number(form.height)||0,size:form.size},token);setQuote(d)}catch(e){toast(e.message)}finally{setBusy(false)}};
 const book=async()=>{if(!quote)return;setBusy(true);try{const d=await api("create-order",{pickup:form.pickup,dropoff:form.dropoff,description:form.description,weight:Number(form.weight)||0,length:Number(form.length)||0,width:Number(form.width)||0,height:Number(form.height)||0,size:form.size},token);await api("notify",{type:"new_delivery",orderId:d.order.id},token).catch(()=>{});setOrders(x=>[d.order,...x]);setSelected(d.order);setQuote(null);setForm({pickup:"",dropoff:"",description:"",weight:"",length:"",width:"",height:"",size:"medium"});toast("Delivery booked. We’ll let you know as soon as your price is ready.")}catch(e){toast(e.message)}finally{setBusy(false)}};
 const pay=async order=>{setBusy(true);try{const d=await api("create-paystack-payment",{orderId:order.id},token);location.href=d.checkoutUrl}catch(e){toast(e.message);setBusy(false)}};
 const confirm=async order=>{const {error}=await supabase.rpc("confirm_delivery",{p_order_id:order.id});if(error)return toast(error.message);toast("Delivery confirmed.");load()};
 const send=async e=>{e.preventDefault();if(!selected||!message.trim())return;const {error}=await supabase.from("chat_messages").insert({order_id:selected.id,sender_id:session.user.id,body:clean(message)});if(error)toast(error.message);else setMessage("")};
 if(!session)return <Landing open={open}/>;
 return <main className="page"><section className="hero"><div><span className="eyebrow">YOUR DELIVERY, MADE EASY</span><h1>Send with ease.<br/><em>We’ll take it from here.</em></h1><p>Book in a few simple steps, follow every update and stay in touch with your rider from pickup to arrival.</p></div><div className="hero-card"><Package size={34}/><strong>Easy from start to finish</strong><span>Book a pickup, pay securely and follow your delivery all the way.</span></div></section>
 <div className="grid"><section className="panel"><h2>Book a dispatch</h2><form onSubmit={getQuote} className="form"><Address label="Pickup address" value={form.pickup} onChange={v=>setForm({...form,pickup:v})} locate={()=>locate("pickup")} locating={loc==="pickup"}/><Address label="Destination address" value={form.dropoff} onChange={v=>setForm({...form,dropoff:v})} locate={()=>locate("dropoff")} locating={loc==="dropoff"}/><label>Package description<textarea required value={form.description} onChange={e=>setForm({...form,description:e.target.value})} placeholder="What are you sending?"/></label><div className="two"><label>Weight (kg)<input type="number" min="0" step=".1" value={form.weight} onChange={e=>setForm({...form,weight:e.target.value})} placeholder="Optional"/></label><label>Package size<select value={form.size} onChange={e=>setForm({...form,size:e.target.value})}><option value="small">Small</option><option value="medium">Medium</option><option value="large">Large</option><option value="very_large">Very large</option></select></label></div><div className="two"><label>Length (cm)<input type="number" min="0" value={form.length} onChange={e=>setForm({...form,length:e.target.value})}/></label><label>Width (cm)<input type="number" min="0" value={form.width} onChange={e=>setForm({...form,width:e.target.value})}/></label></div><label>Height (cm)<input type="number" min="0" value={form.height} onChange={e=>setForm({...form,height:e.target.value})}/></label><button className="primary wide" disabled={busy}>{busy?"Calculating…":"Get my delivery estimate"} <ArrowRight size={18}/></button></form>
 {quote&&<div className="quote"><span className="eyebrow">YOUR DELIVERY ESTIMATE</span><h3>{money(quote.price)}</h3><p><CheckCircle2 size={17}/> A clear estimate now. We’ll confirm your final price before payment.</p><button className="primary wide" onClick={book}>Book this delivery <ArrowRight size={17}/></button></div>}</section>
 <section className="panel"><div className="panel-head"><h2>My deliveries</h2><RefreshCw size={18}/></div>{orders.length===0?<Empty text="Your deliveries will appear here."/>:orders.map(o=><button className={`order ${selected?.id===o.id?"selected":""}`} key={o.id} onClick={()=>setSelected(o)}><div><b>{o.tracking_number}</b><small>{o.pickup_address} → {o.dropoff_address}</small></div><span>{statusLabels[o.status]||o.status}</span><strong>{money(o.final_price)}</strong></button>)}{selected&&<div className="selected-detail"><h3>{selected.tracking_number}</h3><p>{selected.pickup_address} → {selected.dropoff_address}</p><div className="timeline">{["awaiting_payment","paid","accepted","picked_up","on_the_way","at_door","delivered","completed"].map(s=><span className={["completed","delivered","at_door","on_the_way","picked_up","accepted","paid"].includes(selected.status)&&["awaiting_payment","paid","accepted","picked_up","on_the_way","at_door","delivered","completed"].indexOf(s)<=["awaiting_payment","paid","accepted","picked_up","on_the_way","at_door","delivered","completed"].indexOf(selected.status)?"done":""} key={s}/>)}</div>{selected.status==="awaiting_payment"&&<button className="primary wide" onClick={()=>pay(selected)} disabled={busy}>Pay {money(selected.final_price)} securely</button>}{selected.status==="price_review"&&<div className="notice">We’re confirming your delivery price. You’ll be able to pay as soon as it’s ready.</div>}{selected.status==="delivered"&&<button className="primary wide" onClick={()=>confirm(selected)}>Confirm delivery</button>}<a className="track-link" href={`/track?tracking=${encodeURIComponent(selected.tracking_number)}`}>Follow your delivery</a></div>}</section></div>
 {selected&&selected.rider_id&&<section className="panel chat"><div className="panel-head"><div><span className="eyebrow">DELIVERY MESSAGES</span><h2>Chat with your rider</h2>{contact?.rider_name&&<small className="chat-contact">{contact.rider_name} · {contact.rider_phone||"Phone unavailable"}</small>}</div><MessageCircle/></div><div className="chatbox">{chat.map(m=><div className={m.sender_id===session.user.id?"mine":"theirs"} key={m.id}>{m.body}<small>{fmt(m.created_at)}</small></div>)}</div><form className="chat-form" onSubmit={send}><input value={message} onChange={e=>setMessage(e.target.value)} placeholder="Write a message to your rider"/><button className="primary" aria-label="Send message"><Send size={17}/></button></form></section>}
 </main>
}

function Landing({open}){return <main className="landing"><div className="landing-copy"><span className="eyebrow">FEMMADEXDRIVE · DELIVERY MADE EASY</span><h1>Fast dispatch.<br/><em>Care in every delivery.</em></h1><p>From a quick local pickup to a delivery across town, send with confidence. Book simply, pay securely and stay updated until your package arrives.</p><div className="actions"><button className="primary big" onClick={()=>open("customer","signup")}>Send a package <ArrowRight/></button><button className="secondary big" onClick={()=>go("/rider")}><Bike/> Become a rider</button><button className="ghost big" onClick={()=>go("/track")}>Track a delivery</button></div><div className="trust-note"><ShieldCheck size={17}/> Secure checkout <span>·</span> Personal updates <span>·</span> Friendly support</div></div><img src="/images/delivery-hero.svg" alt="FemmaDexDrive delivery rider bringing a package to its destination" className="landing-img"/><section className="cards"><Info icon={<Navigation/>} title="Quick, convenient pickup" text="Arrange a local delivery in just a few simple steps."/><Info icon={<Box/>} title="Handled with care" text="Your package matters. We’ll get it safely from pickup to drop-off."/><Info icon={<ShieldCheck/>} title="Pay with confidence" text="Use secure Paystack checkout and get a clear payment confirmation."/><Info icon={<MessageCircle/>} title="Always in the loop" text="Follow delivery updates and message your rider when assigned."/></section></main>}
function Info({icon,title,text}){return <article className="info"><div>{icon}</div><h3>{title}</h3><p>{text}</p></article>}
function Address({label,value,onChange,locate,locating}){return <label>{label}<div className="address"><MapPin size={17}/><input required value={value} onChange={e=>onChange(e.target.value)} placeholder="Full address, landmark and area"/><button type="button" onClick={locate}>{locating?<span className="spinner small"/>:<LocateFixed size={16}/>}</button></div></label>}
function Empty({text}){return <div className="empty"><Package size={18}/>{text}</div>}

function PaymentResult(){const [status]=useState(new URLSearchParams(location.search).get("status")||"pending");return <main className="center"><CheckCircle2 size={48} color="var(--accent)"/><h1>{status==="success"?"Payment confirmed":"Payment update"}</h1><p>{status==="success"?"Thanks for your payment. Your delivery status will update shortly.":"Your payment is being confirmed. Check your delivery list shortly for the latest update."}</p><button className="primary" onClick={()=>go("/")}>Back to my deliveries</button></main>}
function Tracker(){
 const [tracking,setTracking]=useState(new URLSearchParams(location.search).get("tracking")||""),[order,setOrder]=useState(null),[busy,setBusy]=useState(false),[error,setError]=useState("");
 const find=async e=>{e?.preventDefault();setBusy(true);setError("");try{const d=await api("public-track",{tracking:tracking.trim()});setOrder(d.order)}catch(e){setError(e.message);setOrder(null)}finally{setBusy(false)}};
 useEffect(()=>{if(tracking)find()},[]);
 return <main className="page narrow"><section className="panel"><span className="eyebrow">DELIVERY UPDATES</span><h1>Track your delivery</h1><p>Enter your tracking number to see the latest update on your package.</p><form className="search" onSubmit={find}><input value={tracking} onChange={e=>setTracking(e.target.value.toUpperCase())} placeholder="FDD-XXXXXXXX"/><button className="primary" disabled={busy}>{busy?"Searching…":"Track"}</button></form>{error&&<div className="error">{error}</div>}{order&&<div className="track-result"><div className="order-top"><b>{order.tracking_number}</b><span>{statusLabels[order.status]||order.status}</span></div><p>{order.pickup_area} → {order.dropoff_area}</p><div className="tracking-line">{["accepted","picked_up","on_the_way","at_door","delivered","completed"].map(s=><div key={s} className={order.status===s||order.completed_steps?.includes(s)?"done":""}><i/><small>{statusLabels[s]}</small></div>)}</div><div className="route-meta"><span><Clock3/> Estimated trip: {order.duration_minutes?`${order.duration_minutes} min`:"—"}</span></div></div>}</section></main>
}

function Rider({session,profile,open,toast}){
 const [jobs,setJobs]=useState([]),[active,setActive]=useState(null),[online,setOnline]=useState(profile?.rider?.is_online||false),[message,setMessage]=useState(""),[chat,setChat]=useState([]),[contact,setContact]=useState(null);
 const load=async()=>{if(!session)return;const {data}=await supabase.rpc("get_rider_available_orders");const {data:mine}=await supabase.from("orders").select("*").eq("rider_id",session.user.id).order("created_at",{ascending:false});const all=[...(data||[]),...(mine||[])];setJobs(all);setActive(current=>current?all.find(x=>x.id===current.id)||current:null)};
 useEffect(()=>{if(!session)return;if(profile?.role!=="rider"||profile?.rider?.approval_status!=="approved")return;load();const c=supabase.channel(`rider-${session.user.id}`).on("postgres_changes",{event:"*",schema:"public",table:"orders"},load).subscribe();const timer=setInterval(load,15000);return()=>{clearInterval(timer);supabase.removeChannel(c)}},[session?.user?.id,profile?.role,profile?.rider?.approval_status]);
 useEffect(()=>{setOnline(!!profile?.rider?.is_online)},[profile?.rider?.is_online]);
 useEffect(()=>{if(!active||!session){setChat([]);setContact(null);return}let isCurrent=true;setChat([]);setContact(null);const c=supabase.channel(`rchat-${active.id}`).on("postgres_changes",{event:"INSERT",schema:"public",table:"chat_messages",filter:`order_id=eq.${active.id}`},e=>setChat(x=>x.some(m=>m.id===e.new.id)?x:[...x,e.new])).subscribe();Promise.all([supabase.rpc("get_delivery_contacts",{p_order_id:active.id}),supabase.from("chat_messages").select("*").eq("order_id",active.id).order("created_at")]).then(([contacts,messages])=>{if(!isCurrent)return;if(contacts.error)toast(contacts.error.message);setContact(contacts.data?.[0]||null);if(messages.error){toast(messages.error.message);return}setChat(current=>{const byId=new Map(current.map(m=>[m.id,m]));for(const m of messages.data||[])byId.set(m.id,m);return [...byId.values()].sort((a,b)=>new Date(a.created_at)-new Date(b.created_at))})});return()=>{isCurrent=false;supabase.removeChannel(c)}},[active?.id,session?.user?.id]);
 const presence=async()=>{const n=!online;setOnline(n);navigator.geolocation?.getCurrentPosition(p=>supabase.rpc("update_rider_presence",{p_is_online:n,p_lat:p.coords.latitude,p_lng:p.coords.longitude}),()=>supabase.rpc("update_rider_presence",{p_is_online:n,p_lat:null,p_lng:null}))};
 const accept=async o=>{const {data,error}=await supabase.rpc("accept_order",{p_order_id:o.id});if(error)return toast(error.message);setActive(data);toast("Delivery accepted.");load()};
 const advance=async s=>{const {data,error}=await supabase.rpc("advance_order",{p_order_id:active.id,p_status:s});if(error)return toast(error.message);setActive(data);load();toast(`Updated: ${statusLabels[s]}`)};
 const send=async e=>{e.preventDefault();if(!message.trim()||!active)return;const {error}=await supabase.from("chat_messages").insert({order_id:active.id,sender_id:session.user.id,body:clean(message)});if(error)toast(error.message);else setMessage("")};
 if(!session)return <RiderLanding open={open}/>;
 if(profile?.role!=="rider")return <Blocked title="Rider account required"/>;
 if(profile.rider?.approval_status!=="approved")return <PendingRider session={session} toast={toast}/>;
 return <main className="page"><section className="hero"><div><span className="eyebrow">RIDER PORTAL</span><h1>Take the right jobs.<br/><em>Move them safely.</em></h1><p>Riders see the vehicle requirement and package details, but never the customer's delivery charge.</p><button className={online?"secondary big":"primary big"} onClick={presence}><Radio/> {online?"Go offline":"Go online"}</button></div><img src="/images/rider-hero.svg" className="landing-img" alt="Rider"/></section><div className="grid"><section className="panel"><h2>Available deliveries</h2>{jobs.filter(o=>o.status==="paid"&&!o.rider_id).length===0?<Empty text="No eligible paid delivery is waiting right now."/>:jobs.filter(o=>o.status==="paid"&&!o.rider_id).map(o=><div className="job" key={o.id}><div className="order-top"><b>{o.tracking_number}</b><strong>{o.vehicle_type}</strong></div><p>{o.pickup_address} → {o.dropoff_address}</p><p><Package/> {o.goods_description} · {o.weight_kg||"—"} kg</p><small>{o.distance_km||"—"} km · {o.duration_minutes||"—"} min</small><button className="primary wide" onClick={()=>accept(o)}>Accept delivery</button></div>)}</section><section className="panel"><h2>{active?active.tracking_number:"Active delivery"}</h2>{!active?<Empty text="Accept a delivery to control its stages."/>:<><div className="route"><span>Pickup<br/><b>{active.pickup_address}</b></span><ArrowRight/><span>Destination<br/><b>{active.dropoff_address}</b></span></div><p><strong>Vehicle:</strong> {active.vehicle_type} · <strong>Package:</strong> {active.goods_description}</p><div className="actions">{active.status==="accepted"&&<button className="primary" onClick={()=>advance("picked_up")}>Package picked up</button>}{active.status==="picked_up"&&<button className="primary" onClick={()=>advance("on_the_way")}>Start moving</button>}{active.status==="on_the_way"&&<button className="primary" onClick={()=>advance("at_door")}>Arrived at destination</button>}{active.status==="at_door"&&<button className="primary" onClick={()=>advance("delivered")}>Send delivery confirmation</button>}</div><div className="chat-room-head"><div><span className="eyebrow">PRIVATE DELIVERY CHAT</span><b>{contact?.customer_name||"Customer"}</b></div><span>{contact?.customer_phone||"Phone unavailable"}</span></div><div className="chatbox">{chat.map(m=><div className={m.sender_id===session.user.id?"mine":"theirs"} key={m.id}>{m.body}<small>{fmt(m.created_at)}</small></div>)}</div><form className="chat-form" onSubmit={send}><input value={message} onChange={e=>setMessage(e.target.value)} placeholder="Message customer"/><button className="primary"><Send size={16}/></button></form></>}</section></div></main>
}
function PendingRider({session,toast}){const [bike,setBike]=useState(null),[idFile,setIdFile]=useState(null),[busy,setBusy]=useState(false);const upload=async()=>{if(!bike&&!idFile)return toast("Select a bike/vehicle photo or identity document.");setBusy(true);try{for(const [file,kind] of [[bike,"bike"],[idFile,"identity"]]){if(!file)continue;const path=`${session.user.id}/${kind}-${Date.now()}-${file.name.replace(/[^a-zA-Z0-9._-]/g,"_")}`;const {error}=await supabase.storage.from("rider-documents").upload(path,file,{upsert:false});if(error)throw error;await supabase.from("riders").update(kind==="bike"?{bike_image_path:path}:{identity_document_path:path}).eq("id",session.user.id)}toast("Documents uploaded for operations review.")}catch(e){toast(e.message)}finally{setBusy(false)}};return <main className="center"><div className="setup"><Clock3 size={42}/><h1>Application under review</h1><p>Your rider account is created. Upload the requested verification files so operations can review the application.</p><div className="form"><label>Bike / vehicle photo<input type="file" accept="image/*" onChange={e=>setBike(e.target.files?.[0]||null)}/></label><label>Identity document<input type="file" accept="image/*,.pdf" onChange={e=>setIdFile(e.target.files?.[0]||null)}/></label><button className="primary wide" disabled={busy} onClick={upload}>{busy?"Uploading…":"Submit verification files"}</button></div></div></main>}
function RiderLanding({open}){return <main className="landing"><div><span className="eyebrow">RIDER NETWORK</span><h1>Join the delivery network.</h1><p>Apply with your rider, vehicle and identity information. Operations reviews the application before live dispatch access.</p><div className="actions"><button className="primary big" onClick={()=>open("rider","signup")}>Apply as rider <UserPlus/></button><button className="secondary big" onClick={()=>open("rider","login")}>Rider login <LogIn/></button></div></div><img src="/images/rider-hero.svg" className="landing-img" alt="Rider"/></main>}

function Admin({session,profile,open,toast}){
 const [orders,setOrders]=useState([]),[riders,setRiders]=useState([]),[selected,setSelected]=useState(null),[price,setPrice]=useState("");
 const load=async()=>{if(!session||!["admin","supervisor"].includes(profile?.role))return;const [{data:o},{data:r}]=await Promise.all([supabase.from("orders").select("*,customer:profiles!orders_customer_id_fkey(full_name,email),rider:riders!orders_rider_id_fkey(display_name)").order("created_at",{ascending:false}).limit(200),supabase.from("riders").select("*").order("created_at",{ascending:false})]);const rows=o||[];setOrders(rows);setRiders(r||[]);setSelected(current=>current?rows.find(item=>item.id===current.id)||current:null)};
 useEffect(()=>{if(!session||!["admin","supervisor"].includes(profile?.role))return;load();const c=supabase.channel(`admin-live-${session.user.id}`).on("postgres_changes",{event:"*",schema:"public",table:"orders"},load).on("postgres_changes",{event:"*",schema:"public",table:"riders"},load).subscribe();return()=>supabase.removeChannel(c)},[session?.user?.id,profile?.role]);
 const approve=async(id,yes)=>{const {error}=await supabase.rpc("approve_rider",{p_rider_id:id,p_approved:yes});if(error)return toast(error.message);toast(yes?"Rider approved":"Rider rejected");load()};
 const setFinal=async()=>{if(!selected)return;const {error}=await supabase.rpc("set_order_price",{p_order_id:selected.id,p_price:Number(price)});if(error)return toast(error.message);toast("Final price updated.");load()};
 const active=orders.filter(o=>!["completed","cancelled"].includes(o.status));
 if(!session)return <main className="center"><LockKeyhole/><h1>Admin sign in</h1><button className="primary" onClick={()=>open("admin","login")}>Sign in</button></main>;
 if(!["admin","supervisor"].includes(profile?.role))return <Blocked title="Not authorized"/>;
 return <main className="page"><div className="admin-head"><div><span className="eyebrow">OPERATIONS</span><h1>FemmaDexDrive control</h1><p>Every delivery, payment and rider application is recorded in Supabase.</p></div><button className="secondary" onClick={load}><RefreshCw/> Refresh</button></div><div className="metrics"><Metric n={active.length} t="Active deliveries"/><Metric n={orders.filter(o=>o.status==="completed").length} t="Completed"/><Metric n={riders.filter(r=>r.is_online).length} t="Riders online"/><Metric n={riders.filter(r=>r.approval_status==="pending").length} t="Rider applications"/></div><div className="grid"><section className="panel"><h2>Activity / deliveries</h2>{orders.map(o=><button className="order" key={o.id} onClick={()=>{setSelected(o);setPrice(o.final_price)}}><div><b>{o.tracking_number}</b><small>{o.customer?.full_name||"Customer"} · {fmt(o.created_at)}</small></div><span>{statusLabels[o.status]||o.status}</span><strong>{money(o.final_price)}</strong></button>)}</section><section className="panel"><h2>Rider applications</h2>{riders.filter(r=>r.approval_status==="pending").map(r=><div className="job" key={r.id}><b>{r.display_name}</b><p>{r.vehicle_type} · {r.vehicle_registration}</p><div className="actions"><button className="primary" onClick={()=>approve(r.id,true)}>Approve</button><button className="secondary" onClick={()=>approve(r.id,false)}>Reject</button></div></div>)}{riders.filter(r=>r.approval_status==="pending").length===0&&<Empty text="No pending rider applications."/>}</section></div>{selected&&<section className="panel"><h2>{selected.tracking_number}</h2><div className="detail"><span><small>Customer</small><b>{selected.customer?.full_name}</b></span><span><small>Pickup</small><b>{selected.pickup_address}</b></span><span><small>Destination</small><b>{selected.dropoff_address}</b></span><span><small>Package</small><b>{selected.goods_description} · {selected.weight_kg||"—"} kg</b></span><span><small>Distance</small><b>{selected.distance_km} km</b></span><span><small>Vehicle</small><b>{selected.vehicle_type}</b></span><span><small>System price</small><b>{money(selected.system_price)}</b></span><span><small>Final price</small><div className="inline"><input type="number" value={price} onChange={e=>setPrice(e.target.value)}/><button className="primary" onClick={setFinal}>Save</button></div></span><span><small>Payment</small><b>{selected.payment_status}</b></span><span><small>Status</small><b>{statusLabels[selected.status]||selected.status}</b></span></div></section>}</main>
}
function Metric({n,t}){return <div className="metric"><b>{n}</b><span>{t}</span></div>}

function Auth({role,mode,close,toast}){
 const [email,setEmail]=useState(""),[password,setPassword]=useState(""),[name,setName]=useState(""),[phone,setPhone]=useState(""),[vehicle,setVehicle]=useState(""),[plate,setPlate]=useState(""),[bike,setBike]=useState(null),[idFile,setIdFile]=useState(null),[busy,setBusy]=useState(false),[msg,setMsg]=useState("");
 const submit=async e=>{e.preventDefault();setBusy(true);setMsg("");try{if(mode==="login"){const {data:authData,error:authError}=await supabase.auth.signInWithPassword({email:email.trim(),password});if(authError)throw authError;const {data:profile,error:profileError}=await supabase.from("profiles").select("role").eq("id",authData.user.id).maybeSingle();if(profileError)throw new Error(`Signed in, but your account role could not be loaded: ${profileError.message}`);const actualRole=String(profile?.role||"").toLowerCase();const destination=actualRole==="customer"?"/":actualRole==="rider"?"/rider":["admin","supervisor"].includes(actualRole)?"/admin":null;if(!destination)throw new Error("Your account has no valid profile role. Ask the company to finish setting up your profile.");close();go(destination);toast("Signed in.")}else{if(role==="admin")throw new Error("Admin accounts are created and authorized in Supabase; public signup is disabled.");const {data,error}=await supabase.auth.signUp({email,password,options:{data:{full_name:name,phone,requested_role:role,vehicle_type:vehicle,vehicle_registration:plate}}});if(error)throw error;if(data.user){api("notify",{type:role==="rider"?"new_rider":"new_customer"},data.session?.access_token).catch(()=>{});}if(data.user&&role==="rider"&&(bike||idFile)){toast("Account created. Upload documents from the rider application after email confirmation.")}setMsg(data.session?"Account created.":"Check your email to confirm your account.");} }catch(e){setMsg(e.message)}finally{setBusy(false)}};
 return <div className="modal" onClick={close}><div className="modal-card" onClick={e=>e.stopPropagation()}><button className="close" onClick={close}><X/></button><span className="eyebrow">{role.toUpperCase()}</span><h2>{mode==="signup"?"Create account":"Sign in"}</h2><form className="form" onSubmit={submit}>{mode==="signup"&&<><label>Full name<input required value={name} onChange={e=>setName(e.target.value)}/></label><label>Phone<input required value={phone} onChange={e=>setPhone(e.target.value)}/></label>{role==="rider"&&<><label>Vehicle type<select required value={vehicle} onChange={e=>setVehicle(e.target.value)}><option value="">Select</option><option>Motorcycle</option><option>Car</option><option>Van</option><option>Lorry</option></select></label><label>Plate number<input value={plate} onChange={e=>setPlate(e.target.value)}/></label><label>Bike/vehicle image<input type="file" accept="image/*" onChange={e=>setBike(e.target.files?.[0]||null)}/></label><label>Identity document<input type="file" accept="image/*,.pdf" onChange={e=>setIdFile(e.target.files?.[0]||null)}/></label></>}</>}<label>Email<input type="email" required value={email} onChange={e=>setEmail(e.target.value)}/></label><label>Password<input type="password" {...(mode==="signup"?{minLength:8}:{})} required value={password} onChange={e=>setPassword(e.target.value)}/></label>{mode==="login"&&<button type="button" className="ghost recovery" onClick={async()=>{if(!email)return setMsg("Enter your email first.");const {error}=await supabase.auth.resetPasswordForEmail(email,{redirectTo:`${location.origin}/`});setMsg(error?error.message:"Password reset instructions sent if that account exists.")}}>Forgot password?</button>}{msg&&<div className="notice">{msg}</div>}<button className="primary wide" disabled={busy}>{busy?"Working…":mode==="signup"?"Create account":"Sign in"} <ArrowRight size={17}/></button></form></div></div>
}

function Footer(){return <footer><div><b className="logo">FD</b><strong>FemmaDexDrive</strong><p>Fast, careful deliveries with updates that keep you in the loop.</p></div><div><button onClick={()=>go("/")}>Book dispatch</button><button onClick={()=>go("/rider")}>Join riders</button><button onClick={()=>go("/track")}>Track delivery</button></div><small>© {new Date().getFullYear()} FemmaDexDrive</small></footer>}
